import pygame
import time
print("Chargement des images...")

pygame.init()
pygame.display.set_caption("Le Babelcasino")
largeur, hauteur = 800, 800
fenetre = pygame.display.set_mode((largeur, hauteur))
chargement = [pygame.image.load(f'images/Fonds d\'ecran/Chargement/c{i}.png').convert() for i in range(1,12)]
fenetre.blit(chargement[0], (0, 0))  # Afficher le fond
pygame.display.flip()  # Mettre à jour l'affichage

def charger_et_agrandir(image_path):
    img = pygame.image.load(image_path).convert_alpha()
    return pygame.transform.scale(img, (img.get_width() * 2, img.get_height() * 2))

souris = pygame.image.load('images/curseur.cur').convert_alpha()
fond = pygame.image.load('images/Fonds d\'ecran/Croupier2.png').convert()
chute = [pygame.image.load(f'images/Jeu de combat/Fonds/Chute/_a_frm{i},100.png') for i in range(4)]
eglise = [pygame.image.load(f'images/Jeu de combat/Fonds/Eglise/_a_frm{i},150.png') for i in range(8)]
pluie = [pygame.image.load(f'images/Jeu de combat/Fonds/Pluie/_a_frm{i},120.png') for i in range(8)]
lave = [pygame.image.load(f'images/Jeu de combat/Fonds/Lave/_a_frm{i},100.png') for i in range(8)]
temple = [pygame.image.load(f'images/Jeu de combat/Fonds/Temple/_a_frm{i},100.png') for i in range(8)]
desert = [pygame.image.load(f'images/Jeu de combat/Fonds/Desert/_a_frm{i},80.png') for i in range(8)]
fond3 = pygame.image.load('images/Fonds d\'ecran/enfer2.png').convert()
roulette = pygame.image.load('images/Icones_jeux/roulette2.png').convert_alpha()
roulette2 = pygame.image.load('images/Icones_jeux/roulette3.png').convert_alpha()
diable = charger_et_agrandir('images/Diable.png')
entrer = pygame.image.load('images/Boutons_autre/Entrer-1.png').convert_alpha()
entrer2 = pygame.image.load('images/Boutons_autre/Entrer-2.png').convert_alpha()
retour = pygame.image.load('images/Boutons_autre/Retour-1.png').convert_alpha()
retour2 = pygame.image.load('images/Boutons_autre/Retour-2.png').convert_alpha()
imgpof = pygame.image.load('images/Icones_jeux/pof1.png').convert_alpha()
imgpof2 = pygame.image.load('images/Icones_jeux/pof2.png').convert_alpha()
machine_a_sous2 = pygame.image.load('images/Icones_jeux/machine_a_sous2.png').convert_alpha()
machine_a_sous1 = pygame.image.load('images/Icones_jeux/machine_a_sous1.png').convert_alpha()
blackjack2 = pygame.image.load('images/Icones_jeux/blackjack2.png').convert_alpha()
blackjack1 = pygame.image.load('images/Icones_jeux/blackjack1.png').convert_alpha()
face = charger_et_agrandir('Pile_ou_face/Piece face.png')
pile = charger_et_agrandir('Pile_ou_face/Piece pile.png')
face2 = charger_et_agrandir('Pile_ou_face/Piece face2.png')
pile2 = charger_et_agrandir('Pile_ou_face/Piece pile2.png')
icone = pygame.image.load('images/icone.png').convert_alpha()
paradis = pygame.image.load('images/Fonds d\'ecran/paradis.png').convert_alpha()
fleche_retour = pygame.image.load('images/Boutons_autre/Fleche_retour.png').convert_alpha()
fleche_retour2 = pygame.image.load('images/Boutons_autre/Fleche_retour2.png').convert_alpha()
bouton_play_bj = charger_et_agrandir('images/BoutonPlay1.png')
bouton_play_bj2 = charger_et_agrandir('images/BoutonPlay2.png')
bouton_stop_bj = charger_et_agrandir('images/BoutonStop1.png')
bouton_stop_bj2 = charger_et_agrandir('images/BoutonStop2.png')
maskot = pygame.image.load('images/maskot.png').convert_alpha()
fondbj = pygame.image.load('images/Fonds d\'ecran/fondbj.png').convert_alpha()
abel = pygame.image.load('images/abel.png').convert_alpha()
boutique1 = pygame.image.load('images/Icones_jeux/boutique1.png').convert_alpha()
boutique2 = pygame.image.load('images/Icones_jeux/boutique2.png').convert_alpha()
jeucombat1 = pygame.image.load('images/Icones_jeux/Jeu_combat3.png').convert_alpha()
jeucombat2 = pygame.image.load('images/Icones_jeux/Jeu_combat4.png').convert_alpha()
vodka1 = pygame.transform.scale(pygame.image.load('images/vodka1.png').convert_alpha(),(140,140))
vodka2 = pygame.transform.scale(pygame.image.load('images/Vodka2.png').convert_alpha(),(140,140))
alcool1 = pygame.image.load('images/Icones_jeux/Alcool1.png').convert_alpha()
alcool2 = pygame.image.load('images/Icones_jeux/Alcool2.png').convert_alpha()
whisky1 = pygame.transform.scale(pygame.image.load('images/Whisky1.png').convert_alpha(),(140,140))
whisky2 = pygame.transform.scale(pygame.image.load('images/Whisky2.png').convert_alpha(),(140,140))
mojito1 = pygame.transform.scale(pygame.image.load('images/Mojito1.png').convert_alpha(),(140,140))
mojito2 = pygame.transform.scale(pygame.image.load('images/Mojito2.png').convert_alpha(),(140,140))
biere1 = pygame.transform.scale(pygame.image.load('images/Bière1.png').convert_alpha(),(140,140))
biere2 = pygame.transform.scale(pygame.image.load('images/Bière2.png').convert_alpha(),(140,140))
effet_vodka = charger_et_agrandir('images/Caractéristiques/tab_vodka.png')
effet_biere = charger_et_agrandir('images/Caractéristiques/tab_biere.png')
effet_whisky = charger_et_agrandir('images/Caractéristiques/tab_whisky.png')
effet_mojito = charger_et_agrandir('images/Caractéristiques/tab_mojito.png')
icone_klaxon = pygame.transform.scale(pygame.image.load('images/icone_klaxon.png').convert_alpha(),(140,140))
icone_cryoblade = pygame.transform.scale(pygame.image.load('images/icone_cryoblade.png').convert_alpha(),(140,140))
icone_reeju = pygame.transform.scale(pygame.image.load('images/icone_reeju.png').convert_alpha(),(140,140))
icone_windcliffe = pygame.transform.scale(pygame.image.load('images/icone_windcliffe.png').convert_alpha(),(140,140))
icone_maehv = pygame.transform.scale(pygame.image.load('images/icone_maevh.png').convert_alpha(),(140,140))
icone_zendo = pygame.transform.scale(pygame.image.load('images/icone_zendo.png').convert_alpha(),(140,140))
icone_zukong = pygame.transform.scale(pygame.image.load('images/icone_zukong.png').convert_alpha(),(140,140))
icone_hero = pygame.transform.scale(pygame.image.load('images/icone_hero.png').convert_alpha(),(140,140))
icone_hsuku = pygame.transform.scale(pygame.image.load('images/icone_hsuku.png').convert_alpha(),(140,140))
icone_whistler = pygame.transform.scale(pygame.image.load('images/icones_whistler.png').convert_alpha(),(140,140))
icone_sanguinar = pygame.transform.scale(pygame.image.load('images/icone_sanguinar.png').convert_alpha(),(140,140))
icone_tethermancer = pygame.transform.scale(pygame.image.load('images/icone_tether.png').convert_alpha(),(140,140))
icone_twilight = pygame.transform.scale(pygame.image.load('images/icone_twilight.png').convert_alpha(),(140,140))
icone_pureblade = pygame.transform.scale(pygame.image.load('images/icone_pureblade.png').convert_alpha(),(140,140))
icone_aether = pygame.transform.scale(pygame.image.load('images/icone_aether.png').convert_alpha(),(140,140))
icone_suzumebachi = pygame.transform.scale(pygame.image.load('images/icone_suzumebachi.png').convert_alpha(),(140,140))
icone_yggdra = pygame.transform.scale(pygame.image.load('images/icone_yggdra.png').convert_alpha(),(140,140))
icone_dusk = pygame.transform.scale(pygame.image.load('images/icone_dusk.png').convert_alpha(),(140,140))
info1 = pygame.transform.scale(pygame.image.load('images/Jeu de Combat/Infos/Info.png').convert_alpha(),(100,100))
info2 = pygame.transform.scale(pygame.image.load('images/Jeu de Combat/Infos/Info2.png').convert_alpha(),(100,100))
valider = pygame.image.load("images/Jeu de combat/valider.png").convert_alpha()
img_hero = pygame.image.load('images/Btn_heros/_a_frm0,70.png').convert_alpha()
item_img_biere = pygame.image.load('images/Inventaire/Biere.png').convert_alpha()
item_img_whisky = pygame.image.load('images/Inventaire/Whisky.png').convert_alpha()
item_img_mojito = pygame.image.load('images/Inventaire/Mojito.png').convert_alpha()
item_img_crampons = pygame.image.load('images/Inventaire/Crampons2.png').convert_alpha()
img_crampons = pygame.image.load('images/Inventaire/Crampons.png').convert_alpha()
backpack1 = pygame.image.load('images/Inventaire/Backpack1.png').convert_alpha()
backpack2 = pygame.image.load('images/Inventaire/Backpack2.png').convert_alpha()
valider1 = pygame.image.load('images/Inventaire/valider1.png').convert_alpha()
valider2 = pygame.image.load('images/Inventaire/valider2.png').convert_alpha()
select1 = pygame.image.load('images/Boutons_autre/select1.png').convert_alpha()
select2 = pygame.image.load('images/Boutons_autre/select2.png').convert_alpha()
flecheretour1 = pygame.image.load('images/Inventaire/retourr1.png').convert_alpha()
flecheretour2 = pygame.image.load('images/Inventaire/retourr2.png').convert_alpha()
banniere = pygame.image.load('images/Inventaire/Bannière.png').convert_alpha()
img_podium = charger_et_agrandir('images/Bouton Classement/_a_frm0,40.png')
cartouche_classement = charger_et_agrandir('images/cartouche_classement.png')
cartouche_classement2 = charger_et_agrandir('images/cartouche_classement2.png')
fond_intro = pygame.image.load('images/Fonds d\'ecran/Fond_intro.png').convert_alpha()
fond_dialogues = pygame.image.load('images/Fonds d\'ecran/Dialogues4.png').convert_alpha()
boutons_dialogue1 = pygame.image.load('images/cartouche_classement.png').convert_alpha()
boutons_dialogue2 = pygame.image.load('images/cartouche_classement2.png').convert_alpha()
fond_pnj = pygame.image.load('images/Fonds d\'ecran/Fond_pnj2.png').convert_alpha()

img0 = charger_et_agrandir('images/Digicode/0.png')
img1 = charger_et_agrandir('images/Digicode/1.png')
img2 = charger_et_agrandir('images/Digicode/2.png')
img3 = charger_et_agrandir('images/Digicode/3.png')
img4 = charger_et_agrandir('images/Digicode/4.png')
img5 = charger_et_agrandir('images/Digicode/5.png')
img6 = charger_et_agrandir('images/Digicode/6.png')
img7 = charger_et_agrandir('images/Digicode/7.png')
img8 = charger_et_agrandir('images/Digicode/8.png')
img9 = charger_et_agrandir('images/Digicode/9.png')
imgeffacer = charger_et_agrandir('images/Digicode/effacer.png')
imgvalider = charger_et_agrandir('images/Digicode/valider.png')

pygame.display.set_icon(icone)